services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bpkad-zoom-book-app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - migrate

  migrate:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bpkad-zoom-book-migrate
    command: sh -c 'npx prisma migrate deploy && npx prisma db seed && exit 0'
    env_file:
      - .env
    volumes:
      - ./data:/app/data