services:
  # 1. Database Service (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: bpkad-zoom-app-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - pg.env
    environment:
      - TZ=Asia/Jakarta
      - PGTZ=Asia/Jakarta
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Application Service
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bpkad-zoom-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - pg.env
    environment:
      - TZ=Asia/Jakarta
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: