services:
  migrate:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bpkad-zoom-app-migrate
    env_file:
      - pg.env
    environment:
      - TZ=Asia/Jakarta
    command: sh -c 'npx prisma migrate deploy'
    depends_on:
      - app
  app:
    container_name: bpkad-zoom-app
    depends_on:
      db:
        condition: service_healthy